const { onCall, CallableRequest } = require("firebase-functions/v2/https");
import type { CallableRequest } from 'firebase-functions/lib/common/providers/https';
import * as functions from 'firebase-functions/v1';
const htmlToText = require('html-to-text');
const Handlebars = require('handlebars');

import admin from '../firebase'

const storage = admin.storage().bucket('lwai-3bac8.firebasestorage.app');

const PDFPrinter = require('pdfmake');
const sgMail = require('@sendgrid/mail');
const path = require('path');
const fs = require('fs');
import { config } from '../configs/config-basics';

// const storage = new Storage();

console.log('SendGrid API key loaded:', config.sendgrid_api_key?.slice(0, 5), '...'); 

sgMail.setApiKey(config.sendgrid_api_key);

// const bucketName = 'YOUR_BUCKET_NAME'; // bijv. 'your-project-id.appspot.com'

exports.generateSelfBillingInvoice =  onCall(
    {
        region: 'europe-west1',
        memory: '1GiB',
    },
    async (request: CallableRequest<any>) => {

        // let data:any = request.data;

    try {
        const {
            trainerName,
            trainerAddress,
            trainerVat,
            trainerIban,
            invoiceNumber,
            invoiceDate,
            invoiceDescription,
            amountExcl,
            customerEmail
        } = request.data;

        // const amountExcl = hoursWorked * rate;
        const vatAmount = amountExcl * 0.21;
        const totalIncl = amountExcl + vatAmount;

        const fonts = {
        Roboto: {
            normal: path.join(__dirname, '../fonts/Roboto-Regular.ttf'),
            bold: path.join(__dirname, '../fonts/Roboto-Bold.ttf'),
            italics: path.join(__dirname, '../fonts/Roboto-Italic.ttf'),
        }
        };
        const printer = new PDFPrinter(fonts);

        const docDefinition = {
        content: [
            { text: 'Self-Billing Invoice', style: 'header' },
            { text: `Invoice No: ${invoiceNumber}`, margin: [0, 10, 0, 0] },
            { text: `Date: ${invoiceDate}` },
            { text: `Trainer: ${trainerName}` },
            { text: `Address: ${trainerAddress}` },
            { text: `VAT No: ${trainerVat}` },
            { text: `\nDescription: ${invoiceDescription}` },
            {
            table: {
                widths: ['*', 'auto'],
                body: [
                ['Description', 'Amount'],
                [invoiceDescription, `€${amountExcl.toFixed(2)}`]
                ]
            },
            margin: [0, 10]
            },
            {
            table: {
                widths: ['*', 'auto'],
                body: [
                ['Subtotal (excl. VAT)', `€${amountExcl.toFixed(2)}`],
                ['VAT (21%)', `€${vatAmount.toFixed(2)}`],
                ['Total (incl. VAT)', `€${totalIncl.toFixed(2)}`]
                ]
            },
            layout: 'lightHorizontalLines',
            margin: [0, 20]
            },
            {
            text: `IBAN for payment: ${trainerIban}`,
            margin: [0, 20, 0, 0]
            },
            {
            text: 'This invoice was generated by AliciaLabs on behalf of the trainer (self-billing).',
            italics: true,
            fontSize: 9,
            margin: [0, 30]
            }
        ],
        styles: {
            header: {
            fontSize: 18,
            bold: true
            }
        }
        };

        const pdfDoc = printer.createPdfKitDocument(docDefinition);
        const filePath = `/tmp/invoice-${invoiceNumber}.pdf`;
        const writeStream = fs.createWriteStream(filePath);
        pdfDoc.pipe(writeStream);
        pdfDoc.end();

        await new Promise(resolve => writeStream.on('finish', resolve));

        const destination = `selfbilling-invoices/${invoiceNumber}.pdf`;
        await storage.upload(filePath, {
            destination,
            metadata: { contentType: 'application/pdf' }
        });

        await sgMail.send({
            to: customerEmail,
            from: 'billing@alicialabs.com',
            subject: `Self-Billing Invoice ${invoiceNumber}`,
            text: `Attached is your invoice ${invoiceNumber}.`,
            html: `Attached is your invoice <b>${invoiceNumber}</b>.`,
            attachments: [
                {
                    content: fs.readFileSync(filePath).toString('base64'),
                    filename: `invoice-${invoiceNumber}.pdf`,
                    type: 'application/pdf',
                    disposition: 'attachment'
                }
            ]
        });

        return { success: true };
    } catch (error:any) {
        console.error('Error generating invoice:', error);
        return { success: false, error: error?.message || error || 'Unknown error'};
    }
});


exports.SelfBillingInvoice = functions.region('europe-west1').runWith({ memory: '1GB' }).firestore
  .document('selfBilling/{invoiceId}')
  .onCreate(async (snap: any, context: any) => {
    const emailData = snap.data();
    const templateId = emailData.template || 'selfbilling';
    const language = emailData.language || 'en'; // Fallback naar Engels als geen taal is opgegeven

    // 1. Haal de main template op uit Firestore
    const mainTemplateDoc = await admin.firestore().collection('email_templates').doc('main').get();
    if (!mainTemplateDoc.exists) {
      throw new Error(`Main template not found`);
    }

    const mainTemplate = mainTemplateDoc.data();
    const compiledMainTemplate = Handlebars.compile(mainTemplate[language]);

    // 2. Haal de specifieke template op
    let subject = ''
    let body = ''
    let from = ''
    if(templateId){
      const templateDoc = await admin.firestore().collection('email_templates').doc(templateId).get();
      if (!templateDoc.exists) {
        throw new Error(`Template ${templateId} not found`);
      }

      const template = templateDoc.data();
      subject = template.subject[language] || template.subject['en']; // Fallback naar Engels
      body = template.body[language] || template.body['en']; // Fallback naar Engels
      from = template.from
    }
    else if(emailData.content){
      subject = emailData.content.subject,
      body = emailData.content.body
      from = emailData.content.from
    }

    if(emailData.from){
      from = emailData.from;
    }
    // 3. Vervang placeholders uit de specifieke template
    const compiledTemplate = Handlebars.compile(body);
    const filledTemplateContent = compiledTemplate(emailData.data);
    
    // 5. Vervang placeholders in het subject met de data
    const compiledSubject = Handlebars.compile(subject);
    const finalSubject = compiledSubject(emailData.data);

    // 4. Verwerk de main template met de inhoud van de specifieke template
    const finalHtml = compiledMainTemplate({
      content: filledTemplateContent,
      title: finalSubject,
      subject: finalSubject,
      year: new Date().getFullYear(),
      emailId: emailData.data.emailId || '', // Voeg emailId toe voor tracking
      userId: emailData.data.userId || '', // Voeg userId toe voor tracking
      unsubscribe: emailData.data.unsubscribe || '',
    });


    // 6. Genereer de tekstversie uit de HTML
    const textBody = htmlToText.convert(finalHtml, {
      wordwrap: 130,  // Breek lange regels netjes af
      selectors: [
        { selector: 'a', options: { ignoreHref: true } }  // Links zonder URL weergeven
      ]
    });

    // 7. Bereid de e-mail voor verzending voor
    let emailContent: any = {
      to: emailData.to,
      bcc: 'administratie@alicialabs.com',
      from: from,
      message: {
        subject: finalSubject,
        html: finalHtml,
        text: textBody
      },
      attachments:[]
    };
    if(emailData.replyTo){
      emailContent.replyTo = emailData.replyTo;
    }

    let attachment = await createPdf(emailData.data);
    console.log('Generated PDF attachment at:', attachment);

    if(attachment){
      emailContent.attachments.push({
        content: fs.readFileSync(attachment).toString('base64'),
        filename: `invoice-${emailData.invoiceNumber}.pdf`,
        type: 'application/pdf',
        disposition: 'attachment'
      });
    }

    admin.firestore().collection('debug_logs').add({
      emailContent,
      timestamp: admin.firestore.FieldValue.serverTimestamp(),
      type: 'selfbilling_email'
    });


    let sendObj = {
        to: emailContent.to,
        bcc: 'administratie@alicialabs.com',
        from: emailContent.from,
        subject: emailContent.message.subject,
        html: emailContent.message.html,
        text: emailContent.message.text,
        attachments: emailContent.attachments
    };

    await sgMail.send(sendObj);


    // 8. Voeg de e-mail toe aan de queue voor verzending
    // await admin.firestore().collection('emailsToSend').add(emailContent);

    // await snap.ref.delete();
    return;
  });


async function createPdf(data:any){
    const {
            trainerName,
            trainerAddress,
            trainerVat,
            trainerIban,
            invoiceNumber,
            invoiceDate,
            invoiceDescription,
            amountExcl,
            trainerChamber,
            postal_code,
            city,
            country
        } = data;

        // const amountExcl = hoursWorked * rate;
        const vatAmount = amountExcl * 0.21;
        const totalIncl = amountExcl + vatAmount;

        const fonts = {
        Roboto: {
            normal: path.join(__dirname, '../fonts/Roboto-Regular.ttf'),
            bold: path.join(__dirname, '../fonts/Roboto-Bold.ttf'),
            italics: path.join(__dirname, '../fonts/Roboto-Italic.ttf'),
        }
        };
        const printer = new PDFPrinter(fonts);
        const logoBase64 = fs.readFileSync(path.join(__dirname, '../fonts/logo_alicialabs.txt'), 'utf8');

        const docDefinition = {
            content: [
                {
                columns: [
                    {
                        width: '*',
                        stack: [
                            { 
                                text: 'Self-Billing Invoice', style: 'header',
                                margin: [0, 10]
                            },
                            { text: `${trainerName}`},
                            { text: `${trainerAddress}` },
                            { text: `${postal_code} ${city}` },
                            { text: `${country}` },
                            { text: '', margin: [0, 10] },
                            { text: `Chamber of Commerce: ${trainerChamber || ''}` },
                            { text: `VAT No: ${trainerVat}` },
                            { text: '', margin: [0, 10] },
                            { text: `Date: ${invoiceDate}` },
                            { text: `Invoice No: ${invoiceNumber}`, margin: [0, 5, 0, 0] },
                        ]
                    },
                    {
                        width: 200,
                        image: logoBase64,
                        fit: [200, 200],
                        alignment: 'right'
                    }
                ],
                columnGap: 20,
                margin: [0, 0, 0, 20]
                },

                // { text: `Description: ${invoiceDescription}` },
                {
                    table: {
                        widths: ['*', 'auto'],
                        body: [
                            ['Description', 'Amount'],
                            [invoiceDescription, `€${amountExcl.toFixed(2)}`]
                        ]
                    },
                    layout: 'lightHorizontalLines',
                    margin: [0, 10]
                },
                {
                    table: {
                        widths: ['*', 'auto'],
                        body: [
                        ['Subtotal (excl. VAT)', `€${amountExcl.toFixed(2)}`],
                        ['VAT (21%)', `€${vatAmount.toFixed(2)}`],
                        ['Total (incl. VAT)', `€${totalIncl.toFixed(2)}`]
                        ]
                    },
                    layout: 'lightHorizontalLines',
                    margin: [0, 20]
                },
                {
                text: `IBAN for payment: ${trainerIban}`,
                margin: [0, 20, 0, 0]
                },
                {
                text: 'This invoice was generated by AliciaLabs on behalf of the trainer (self-billing).',
                italics: true,
                fontSize: 9,
                margin: [0, 30]
                }
            ],
            styles: {
                header: {
                fontSize: 18,
                bold: true
                }
            }
            };

        const pdfDoc = printer.createPdfKitDocument(docDefinition);
        const filePath = `/tmp/invoice-${invoiceNumber}.pdf`;
        const writeStream = fs.createWriteStream(filePath);
        pdfDoc.pipe(writeStream);
        pdfDoc.end();

        await new Promise(resolve => writeStream.on('finish', resolve));

        // await saveToStorage(filePath, invoiceNumber);
        return filePath;
        
}


// async function saveToStorage(filePath:string, invoiceNumber:string){
//     const destination = `selfbilling-invoices/${invoiceNumber}.pdf`;
//     await storage.upload(filePath, {
//         destination,
//         metadata: { contentType: 'application/pdf' }
//     });
//     let file = storage.file(destination);

//   await file.makePublic();
//   return 'https://storage.googleapis.com/' + storage.name + '/' + destination;
// }
